# Generated by Django 4.0 on 2021-12-22 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEventDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('no_of_opening', models.IntegerField()),
                ('last_opened_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('email_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.emaileventdatabase')),
            ],
        ),
    ]
