# Generated by Django 4.0 on 2022-01-13 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEventDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('no_of_opening', models.IntegerField(default=-1)),
                ('last_opened_time', models.DateTimeField(auto_now=True)),
                ('last_used_ip', models.CharField(max_length=100, null=True)),
                ('last_location', models.CharField(default='--', max_length=1000)),
            ],
            options={
                'ordering': ['-last_opened_time'],
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('location', models.CharField(default='--', max_length=1000)),
                ('email_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.emaileventdatabase')),
            ],
        ),
    ]
