# Generated by Django 4.0 on 2021-12-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaileventdatabase',
            name='last_opened_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emaileventdatabase',
            name='no_of_opening',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ip',
            name='location',
            field=models.CharField(default='--', max_length=1000),
        ),
    ]
