# Generated by Django 4.0 on 2021-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_emaileventdatabase_last_opened_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaileventdatabase',
            options={'ordering': ['-last_opened_time']},
        ),
        migrations.AddField(
            model_name='emaileventdatabase',
            name='last_location',
            field=models.CharField(default='--', max_length=1000),
        ),
        migrations.AddField(
            model_name='emaileventdatabase',
            name='last_used_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emaileventdatabase',
            name='no_of_opening',
            field=models.IntegerField(default=-1),
        ),
    ]
