# Generated by Django 4.0 on 2022-01-13 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_emaileventdatabase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaileventdatabase',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 13, 17, 8, 32, 874867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
